name: pre-commit

on:
  pull_request:
  push:
    branches: [main]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/create-github-app-token@v1
      id: app-token
      with:
          app-id: 991512
          private-key: ${{ secrets.APP }}
          owner: ${{ github.repository_owner }}
    - name: Setup credentials to access private repositories
      run: git config --global url.https:///x-access-token:${{ steps.app-token.outputs.token }}@github.com/.insteadOf https://github.com/
    - uses: actions/checkout@v4
    - uses: pre-commit/action@v3.0.1

